services:
  user-api:
    build: ./user-api
    restart: always
    networks:
      - app-network
    volumes:
      - shared-data:/usr/src/shared # Ensure shared volume is used for admin_info.json
      - user-api-data:/usr/src/user-api/common/data # Dedicated volume for user-api database

  general-api:
    build: ./general-api
    restart: always
    networks:
      - app-network
    depends_on:
      - selenium
    volumes:
      - general-api-data:/usr/src/general-api/common/data # Dedicated volume for general-api database

  central-webserver:
    build: ./central-webserver
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - user-api
      - general-api
    volumes:
      - shared-data:/usr/src/shared # This is necessary for DB_KEY access

  selenium:
    image: seleniarm/standalone-chromium
    platform: linux/amd64
    restart: always
    networks:
      - app-network
    ports:
      - "4444:4444" # Selenium WebDriver Port
      - "7900:7900" # VNC Debugging (optional)
    shm_size: '2g' # Prevent crashes due to lack of shared memory
    environment:
      - SE_NODE_MAX_SESSIONS=5 # Allows multiple parallel browser sessions
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_SESSION_TIMEOUT=30

volumes:
  shared-data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/docker-volumes/shared-data
      o: bind
  user-api-data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/docker-volumes/user-api-data
      o: bind
  general-api-data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/docker-volumes/general-api-data
      o: bind

networks:
  app-network:
    driver: bridge
